### ISSUE TITLE
No microphone playback

### ISSUE THREAD

**Issue by karolthepolski** [newventuresoftware/WaveformControl#7]
Hello, i'm creating music visualizer. I'm just curious how did you disabled microphone playback in your app. In my app i got playback as soon as i do "audioTrack.play()". It's pretty annoying as it gives feedback and it can get pretty nasty sometimes. Is there any trick to disable it?

**Comment by yavor87** [comment]
Hey Karol,

What do you mean you have microphone playback when you play an audiotrack?

On Oct 10, 2017 11:44, "Karol Ziolkowski" <notifications@github.com> wrote:

Hello, i'm creating music visualizer. I'm just curious how did you disabled
microphone playback in your app. In my app i got playback as soon as i do
"audioTrack.play()". It's pretty annoying as it gives feedback and it can
get pretty nasty sometimes. Is there any trick to disable it?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/newventuresoftware/WaveformControl/issues/7>, or mute
the thread

**Comment by karolthepolski** [comment]
Wow, that was a fast reaction. It's not really an issue on your app - here it works as i would like my app to work.

In my app the recorded sound is instantly played on speaker, your app doesn't have that issue. Is there anything in the code which makes recorded sound not being played on the device?

**Comment by yavor87** [comment]
There shouldn't be anything that prevents playback.

Karol, do you mind sharing more details about your app? What is it, what
it's doing and I can help you with the issue. I am not sure I understand
the issue now. Knowing what the app does and looking at the code will help.
Mail me directly at yavor(at)newventuresoftware.com to continue this
conversation out of public eye.

On Oct 10, 2017 12:03, "Karol Ziolkowski" <notifications@github.com> wrote:

Wow, that was a fast reaction. It's not really an issue on your app - here
it works as i would like my app to work.

In my app the recorded sound is instantly played on speaker, your app
doesn't have that issue. Is there anything in the code which makes recorded
sound not being played on the device?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/newventuresoftware/WaveformControl/issues/7#issuecomment-335408880>,
or mute the thread
